In [ ]:
from google.colab import files
uploaded = files.upload()

Saving student-por.csv to student-por.csv

In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('student-por.csv')

In [ ]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [ ]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
644,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
645,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
646,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
647,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
648,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

In [ ]:
df.shape

(649, 33)

In [ ]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64
 7   Fedu        649 non-null    int64
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64
 13  studytime   649 non-null    int64
 14  failures    649 non-null    int64
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64
 24  freetime    649 non-null    int64
 25  goout       649 non-null    int64
 26  Dalc        649 non-null    int64
 27  Walc        649 non-null    int64
 28  health      649 non-null    int64
 29  absences    649 non-null    int64
 30  G1          649 non-null    int64
 31  G2          649 non-null    int64
 32  G3          649 non-null    int64
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

In [ ]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000,649.000000
mean,16.744222,2.514638,2.306626,1.568567,1.930663,0.221880,3.930663,3.180277,3.184900,1.502311,2.280431,3.536210,3.659476,11.399076,11.570108,11.906009
std,1.218138,1.134552,1.099931,0.748660,0.829510,0.593235,0.955717,1.051093,1.175766,0.924834,1.284380,1.446259,4.640759,2.745265,2.913639,3.230656
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,2.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000

In [ ]:
df.size

21417

In [ ]:
df.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [ ]:
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [ ]:
df.columns = df.columns.str.strip().str.lower()

In [ ]:
df.head()

,school,sex,age,address,famsize,pstatus,medu,fedu,mjob,fjob,...,famrel,freetime,goout,dalc,walc,health,absences,g1,g2,g3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [ ]:
df['g3']

0      11
1      11
2      12
3      14
4      13
       ..
644    10
645    16
646     9
647    10
648    11
Name: g3, Length: 649, dtype: int64

In [ ]:
df['g2']

0      11
1      11
2      13
3      14
4      13
       ..
644    11
645    15
646    12
647    10
648    11
Name: g2, Length: 649, dtype: int64

In [ ]:
df['g1']

0       0
1       9
2      12
3      14
4      11
       ..
644    10
645    15
646    11
647    10
648    10
Name: g1, Length: 649, dtype: int64

In [ ]:
# acg of all numeric columns
df.mean(numeric_only=True)

age           16.744222
medu           2.514638
fedu           2.306626
traveltime     1.568567
studytime      1.930663
failures       0.221880
famrel         3.930663
freetime       3.180277
goout          3.184900
dalc           1.502311
walc           2.280431
health         3.536210
absences       3.659476
g1            11.399076
g2            11.570108
g3            11.906009
dtype: float64

In [ ]:
df ['g2'].mean()

np.float64(11.570107858243452)

In [ ]:
# find the best mark from g3
df ['g3'].max()

19

In [ ]:
df['g3'].min()

0

In [ ]:
df ['g2'].min()

0

In [ ]:
# what if i need the full detail of the best student
best_student = df.loc[df['g3'].idxmax()]
best_student

school                GP
sex                    F
age                   17
address                R
famsize              LE3
pstatus                T
medu                   3
fedu                   1
mjob            services
fjob               other
reason        reputation
guardian          mother
traveltime             2
studytime              4
failures               0
schoolsup             no
famsup               yes
paid                  no
activities            no
nursery              yes
higher               yes
internet              no
romantic              no
famrel                 3
freetime               1
goout                  2
dalc                   1
walc                   1
health                 3
absences               0
g1                    18
g2                    19
g3                    19
Name: 338, dtype: object

In [ ]:
df ['g3'].idxmax()

338

In [ ]:
# find the above avg

avg_score = df['g3'].mean()
avg_score

np.float64(11.906009244992296)

In [ ]:
above_avg_students = df[df['g3'] > avg_score]
above_avg_students[['g3']]

     g3
2    12
3    14
4    13
5    13
6    13
..   ..
634  16
636  19
638  16
641  15
645  16

[348 rows x 1 columns]

In [ ]:
above = (df['g3'] > avg_score).sum()
print("above avg count : ",above)

above avg count :  348

In [ ]:
df = pd.read_csv(r"student-por.csv")


df.columns = df.columns.str.strip().str.lower()

print("Initial sex unique values:", df['sex'].unique())
print("Initial education unique values:", df['schoolsup'].unique())

Initial sex unique values: ['F' 'M']
Initial education unique values: ['yes' 'no']

In [ ]:
# Correctly map 'self_employed' after stripping whitespace from values
df['sex'] = df['sex'].str.strip().map({'F': 1, 'M': 0})

# Verify the unique values after correction
print(df['sex'].unique())

[1 0]

In [ ]:
df['sex'].unique()

array([1, 0])

In [ ]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'pstatus', 'medu', 'fedu',
       'mjob', 'fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'dalc',
       'walc', 'health', 'absences', 'g1', 'g2', 'g3'],
      dtype='object')

In [ ]:
x=df.drop(columns=['g3'],axis=1)

In [ ]:
x=df.drop(columns=['g3'],axis=1)
y=df['g3']

In [ ]:
x=df.drop(columns=['dalc'])
y=df['dalc']

In [ ]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
import pandas as pd

x_train_encoded = pd.get_dummies(x_train, drop_first=True)
x_test_encoded = pd.get_dummies(x_test, drop_first=True)

lr=LinearRegression()
lr.fit(x_train_encoded,y_train)

LinearRegression()

In [ ]:
y_train_pred = lr.predict(x_train_encoded)
y_test_pred = lr.predict(x_test_encoded)

#prediction on both train and test data

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score


mae=mean_absolute_error(y_train,y_train_pred)
mse=mean_squared_error(y_train,y_train_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_train,y_train_pred)

print('mae',mae)
print('mse',mse)
print('rmse',rmse)
print('r2',r2)

mae 0.4867171826774223
mse 0.4885792911407953
rmse 0.6989844713159193
r2 0.4819221552255859

In [ ]:
#rmse-it brings the error back to the original price unit ,
train_r2=r2_score(y_train,y_train_pred)
test_r2=r2_score(y_test,y_test_pred)
print('train_r2',train_r2)
print('test_r2',test_r2)

train_r2 0.4819221552255859
test_r2 0.14015265486039163

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
# the reason for using mae,mse,rmse,r2 is that we neve judge a model by accuracy in LinaerRegression
# here we use error based matrics

mae = mean_absolute_error(y_test,y_test_pred)
mse = mean_squared_error(y_test,y_test_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test,y_test_pred)

print('MAE',mae)
print('MSE',mse)
print('RMSE',rmse)
print('R2',r2)

MAE 0.47254638899308954
MSE 0.42046026391915525
RMSE 0.6484290739311087
R2 0.14015265486039163